### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Thijxx** [SpenceKonde/AVR-Guidance#6]
I was wondering how you do UPD and Serial togther but the link all the way on the end of this page (last line) is dead:
`https://github.com/SpenceKonde/AVR-Guidance/blob/master/UPDI/jtag2updi.md`

**Comment by SpenceKonde** [comment]
The photo was just a picture of a tinyavr with  an srerial adapter pligged in in the normal way, and a second serial adapter pobti a dufferebt jheader, it contains nothing inbtetesting.
